INSERT INTO gundam (name, release_year, grade, series, box_art) VALUES
('Aile Strike Gundam (Revive)', 2014, 'HG', 'Mobile Suit Gundam SEED', 'HGCE_171_GAT-X105_Aile_Strike_Gundam_Revive.jpg'),
('Full Armor Gundam', 2015, 'HG', 'Mobile Suit Gundam Thunderbolt', 'HGGT_Full_Armor_Gundam.jpg'),
('Zaku II (Red Comet Ver.)', 2015, 'HG', 'Mobile Suit Gundam Thunderbolt', 'HGGTO_024_MS-06S_Zaku_II_Red_Comet_Ver.jpg'),
('Gelgoog Jäger', 2010, 'HG', 'Mobile Suit Gundam 0080: War in the Pocket', 'HGUC_045_Gelgoog_Jaegar.webp'),
('Kämpfer', 2008, 'HG', 'Mobile Suit Gundam 0080: War in the Pocket', 'HGUC_089_MS-18E_Kampfer.jpg'),
('Jesta', 2013, 'HG', 'Mobile Suit Gundam Unicorn', 'HGUC_130_RGM-96X_Jesta.jpg'),
('GM Sniper II', 2012, 'HG', 'Mobile Suit Gundam 0080: War in the Pocket', 'HGUC_146_GM_Sniper_II.webp'),
('Gundam Mk-II (Titans)', 2015, 'HG', 'Mobile Suit Zeta Gundam', 'HGUC_194_RX-178_Gundam_Mk-II_Titans.webp'),
('Gundam Ground Type', 2017, 'HG', 'Mobile Suit Gundam: The 08th MS Team', 'HGUC_210_RX-79[G]_Gundam_Ground_Type.webp'),
('Full Armor Gundam Ver.Ka', 2016, 'MG', 'Mobile Suit Gundam Thunderbolt', 'MG_Full_Armor_Gundam_Ver.Ka.webp'),
('Gundam Barbatos', 2019, 'MG', 'Mobile Suit Gundam: Iron-Blooded Orphans', 'MG_Gundam_Barbatos.webp'),
('Sazabi Ver.Ka', 2013, 'MG', 'Mobile Suit Gundam: Char''s Counterattack', 'MG_MSN-04_Sazabi_Ver.Ka.jpg'),
('Jesta', 2013, 'MG', 'Mobile Suit Gundam Unicorn', 'MG_RGM-96X_Jesta.jpg'),
('Wing Gundam Zero EW Ver.Ka', 2020, 'MG', 'Mobile Suit Gundam Wing: Endless Waltz', 'MG_Wing_Gundam_Zero_EW_Ver.Ka.webp'),
('Gundam Exia', 2009, 'PG', 'Mobile Suit Gundam 00', 'PG_GN-001_Gundam_Exia.webp'),
('Gundam Astray Red Frame', 2009, 'PG', 'Mobile Suit Gundam SEED Astray', 'PG_MBF-P02_Gundam_Astray_Red_Frame.webp'),
('Unicorn Gundam', 2014, 'PG', 'Mobile Suit Gundam Unicorn', 'PG_Unicorn_Gundam_RX-0.webp'),
('Zaku II', 2018, 'RG', 'Mobile Suit Gundam', 'RG_04_MS-06F_Zaku_II.jpg'),
('Gundam GP01Fb', 2013, 'RG', 'Mobile Suit Gundam 0083: Stardust Memory', 'RG_13_Gundam_GP01Fb.webp'),
('Nu Gundam', 2019, 'RG', 'Mobile Suit Gundam: Char''s Counterattack', 'RG_32_RX-93_Nu_Gundam.webp'),
('RX-78-2 Gundam Ver.2.0', 2024, 'RG', 'Mobile Suit Gundam', 'RG_40_RX-78-2_Gundam_Ver._2.0.webp');